name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Upload files via FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /test.codeascend.xyz/ # Ensure the server directory exists
          exclude: |
            .git*
            .github/
            node_modules/
            *.test.js
            *.md
          verbose: true # Enable detailed logs for debugging
